randomize();
audio_group_load(audiogroup_default);
loading = false;
blink = false;
pos = -2;
current_seed = noone;
draw_set_color(c_black);
global.id_counter = 0;
blink_timer = 15;
room_speed = 60;
//window_set_fullscreen(false);
